In [1]:
import tensorflow as tf

In [9]:
a = tf.constant([1,2,3])
b = tf.constant([4, 5, 3])

print(a)
print(b)

tf.Tensor([1 2 3], shape=(3,), dtype=int32)
tf.Tensor([4 5 3], shape=(3,), dtype=int32)


In [11]:
print(tf.abs(a-b))

tf.Tensor([3 3 0], shape=(3,), dtype=int32)


In [12]:
print(tf.concat([a,b], axis=0))

tf.Tensor([1 2 3 4 5 3], shape=(6,), dtype=int32)


In [13]:
c = tf.constant([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
c

<tf.Tensor: shape=(2, 2, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])>

In [23]:
d = tf.reshape(c, [2,-1])
print(d)

tf.Tensor(
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]], shape=(2, 6), dtype=int32)


In [17]:
c.shape

TensorShape([2, 2, 3])

In [24]:
tf.reduce_mean(d, axis=0)


<tf.Tensor: shape=(6,), dtype=int32, numpy=array([4, 5, 6, 7, 8, 9])>

In [39]:
e = enumerate(b)
e

In [40]:
g = sorted(e, key=lambda x: x[1].numpy())
g

[(2, <tf.Tensor: shape=(), dtype=int32, numpy=3>),
 (0, <tf.Tensor: shape=(), dtype=int32, numpy=4>),
 (1, <tf.Tensor: shape=(), dtype=int32, numpy=5>)]

In [42]:
g[0:2]

[(2, <tf.Tensor: shape=(), dtype=int32, numpy=3>),
 (0, <tf.Tensor: shape=(), dtype=int32, numpy=4>)]

In [49]:
h = [i for (i,j) in g[0:int(len(g)*0.9)]]
h = sorted(h)
h

[0, 2]

In [47]:
d

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])>

In [50]:
tf.gather(d, indices=h, axis=1)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[1, 3],
       [7, 9]])>